### ISSUE TITLE
Add a Reddit option

### ISSUE THREAD

**Issue by phil-s** [sshaw/copy-as-format#7]
Reddit confuses people a lot, because its current default front-end supports code formatting options which are not supported by the old front-end (and reddit has shown no interest in fixing this long-standing problem).  Consequently people using the default front-end have no idea that the code they paste is liable to look incredibly broken for many of their readers, unless someone points it out to them.

The single formatting technique which is compatible between the old and the new is to indent everything by 4 spaces.  If `copy-as-format` had a reddit option which did that, that would help to reduce the number of broken posts seen at https://old.reddit.com/r/emacs

**Comment by sshaw** [comment]
Hi, yeah that new editor is horrible (but not as bad as Jira/Bitbucket's new editor!). 

This package supports Markdown, which indents everything by 4 spaces so doesn't that solve the issue? Or are you suggesting I add Reddit as an alias for Markdown? Or, something else?

**Comment by phil-s** [comment]
> add Reddit as an alias for Markdown?

Yes, that sounds right.  I'd suggest a Reddit-specific docstring, though, to explain why it uses the 4-space indent, as opposed to some other format which the user might believe is ok to use.

My thinking is that unless there's a named Reddit option, the only 'new' Reddit front-end users who would use the Markdown option would be the ones who were already aware of the problem; whereas explicitly named support for Reddit would address the larger issue of users who have no idea that the problem even exists.

**Comment by sshaw** [comment]
>  I'd suggest a Reddit-specific docstring, though, to explain why it uses the 4-space indent, as opposed to some other format which the user might believe is ok to use.

Reddit's editor supports Markdown. So seems we'd be explaining why Reddit chose Markdown or why Markdown chose 4 spaces, no?

In general I'd be opposed to this addition since all formats that are services/sites in this package are specific to that service/site (GitHub flavored Markdown being the exception). 

10s or 100s of services support Markdown so why would one list Reddit and not Hacker News? Though, actually I don't think Hacker News supports Markdown 🤔 but, you get my drift. 

That being said, from a marketing perspective sure makes sense to add so I likely will but I'm curious on your thoughts on the above.

**Comment by phil-s** [comment]
I see now that I was missing something important :(

I've never used Reddit's 'fancy' editor before, and I didn't realise that they forced you to explicitly switch to a 'markdown' mode if you wanted to use that.

Moreover, I had no idea that if you pasted markdown-indented text into the 'fancy' editor, it would break the formatting!  When I tried that, the indentation was removed, and blank lines were inserted between each pasted line.

That's **awful**.

If I have this correct, then I withdraw the suggestion.  If the user needs to explicitly say "I want to edit using markdown" before pasting an indented code block will *actually work*, then my idea is completely redundant.

**Comment by sshaw** [comment]
>  If the user needs to explicitly say "I want to edit using markdown" before pasting an indented code block will actually work, then my idea is completely redundant.

Yes, this is the case: https://www.reddit.com/wiki/markdown#wiki_differences_between_fancy_pants_and_markdown

Rich Text Editors: Just say no. 

But, if you want to experience the epitome of shit editors, have a look at Jira or Bitbucket's (via opt-in).
