### ISSUE TITLE
New formats: IM

### ISSUE THREAD

**Issue by Ypot** [sshaw/copy-as-format#8]
Could you please add Telegram and Whatsapp formats?

**Comment by sshaw** [comment]
Don't they use markdown?

**Comment by Ypot** [comment]
Hi!!
I don't think so...

I have found this "markdown" for telegram:

```
    **Bold text** – double asterisks from both sides of the text.
    __Italic text__ – double underscore.
    ~~Strikethrough text~~ – double tilde.
    `Monospaced text` – one apostrophe.
    “`Monospaced text 2“` – three apostrophes, it will allow you to use a new line symbol (basically, to make multiple lines of text monospaced). It is different from the mono via context menu (on Mac it is without color and won’t be copied to the clipboard on both Windows and MacOS on the click, because of this to format multiple lines, better use the context menu).
```

**Comment by sshaw** [comment]
Hi, thanks. It is basically GitHub Flavored Markdown given your example and the docs here https://core.telegram.org/api/entities Though this library currently only supports code formatting. Not sure how it would support bold, etc... 

For WhatsApp there is only 1 format: https://faq.whatsapp.com/539178204879377

Checkout the [telegram](https://github.com/sshaw/copy-as-format/tree/telegram) branch here where I added WhatsApp and Telegram and let me know how it goes.

**Comment by sshaw** [comment]
@Ypot did that branch work for you?

**Comment by Ypot** [comment]
Hi!
If I eval "copy-as-format-telegram" I get this. Maybe I don't understand it:
```

```org
* Headline
_aaa_ *fff* adfasf /fasdfas/ fsafa +asfdsadfsa+
```

```

**Comment by sshaw** [comment]
> If I eval "copy-as-format-telegram" I get this. Maybe I don't understand it:

When pasted into Telegram that should result in formatted org mode code: https://core.telegram.org/api/entities. Is that not the case?

**Comment by sshaw** [comment]
Just tested myself and found bug in WhatsApp formatting. Fix it and merged the branch into master. So for Telegram and WhatsApp support try that.
